### ISSUE TITLE
项目运行

### ISSUE THREAD

**Issue by lbyczzz** [zuisong/rs-chinese-chess#1]
请问下项目是如何运行的啊，最近在学习rust，刚刷完一本书，想用您的项目看看，想先跑起来。

**Comment by zuisong** [comment]
项目下载下来之后直接运行 ui 模块
```
 cargo run --bin ui 
```

**Comment by lbyczzz** [comment]
好的，谢谢您。

**Comment by lbyczzz** [comment]
你好，我运行你项目时有一个creates报错error: failed to run custom build command for `fltk-sys v1.4.13`，我rust是rustc 1.75.0-nightly版本的，请问怎么解决啊，我百度了好多方案没用。

**Comment by zuisong** [comment]
方便贴一下全部的日志吗？

**Comment by lbyczzz** [comment]
root@local-xtc:/data/rust_pro/rs-cchess# cargo run --bin ui 
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /data/rust_pro/rs-cchess/lib/ui/Cargo.toml
workspace: /data/rust_pro/rs-cchess/Cargo.toml
    Updating crates.io index
  Downloaded matchers v0.1.0
  Downloaded quote v1.0.33
  Downloaded cfg-if v1.0.0
  Downloaded cmake v0.1.50
  Downloaded lazy_static v1.4.0
  Downloaded overload v0.1.1
  Downloaded thread_local v1.1.7
  Downloaded anyhow v1.0.75
  Downloaded once_cell v1.18.0
  Downloaded bitflags v2.4.0
  Downloaded tracing-log v0.1.3
  Downloaded paste v1.0.14
  Downloaded nu-ansi-term v0.46.0
  Downloaded proc-macro2 v1.0.67
  Downloaded pin-project-lite v0.2.13
  Downloaded log v0.4.20
  Downloaded tracing-attributes v0.1.26
  Downloaded getrandom v0.2.10
  Downloaded smallvec v1.11.1
  Downloaded unicode-ident v1.0.12
  Downloaded crossbeam-utils v0.8.16
  Downloaded bytes v1.5.0
  Downloaded sharded-slab v0.1.4
  Downloaded cc v1.0.83
  Downloaded tracing-core v0.1.31
  Downloaded tracing v0.1.37
  Downloaded crossbeam-channel v0.5.8
  Downloaded memchr v2.6.3
  Downloaded regex-automata v0.1.10
  Downloaded ttf-parser v0.20.0
  Downloaded fltk v1.4.15
  Downloaded aho-corasick v1.1.1
  Downloaded tracing-subscriber v0.3.17
  Downloaded regex v1.9.5
  Downloaded syn v2.0.37
  Downloaded regex-syntax v0.6.29
  Downloaded regex-syntax v0.7.5
  Downloaded regex-automata v0.3.8
  Downloaded libc v0.2.148
  Downloaded fltk-sys v1.4.15
  Downloaded 40 crates (12.7 MB) in 3m 40s (largest was `fltk-sys` at 8.3 MB)
   Compiling libc v0.2.148
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.67
   Compiling unicode-ident v1.0.12
   Compiling memchr v2.6.3
   Compiling once_cell v1.18.0
   Compiling regex-syntax v0.7.5
   Compiling cc v1.0.83
   Compiling quote v1.0.33
   Compiling aho-corasick v1.1.1
   Compiling crossbeam-utils v0.8.16
   Compiling cmake v0.1.50
   Compiling syn v2.0.37
   Compiling fltk-sys v1.4.15
   Compiling regex-automata v0.3.8
   Compiling tracing-core v0.1.31
   Compiling lazy_static v1.4.0
   Compiling regex-syntax v0.6.29
   Compiling paste v1.0.14
   Compiling log v0.4.20
   Compiling regex v1.9.5
   Compiling tracing-attributes v0.1.26
   Compiling regex-automata v0.1.10
   Compiling pin-project-lite v0.2.13
   Compiling anyhow v1.0.75
   Compiling overload v0.1.1
   Compiling nu-ansi-term v0.46.0
   Compiling matchers v0.1.0
   Compiling crossbeam-channel v0.5.8
   Compiling tracing v0.1.37
   Compiling tracing-log v0.1.3
   Compiling sharded-slab v0.1.4
   Compiling getrandom v0.2.10
   Compiling thread_local v1.1.7
   Compiling smallvec v1.11.1
   Compiling bitflags v2.4.0
   Compiling ttf-parser v0.20.0
   Compiling engine v0.1.0 (/data/rust_pro/rs-cchess/lib/engine)
warning: unused import: `crate::board::*`
  --> lib/engine/src/zobrist.rs:97:9
   |
97 |     use crate::board::*;
   |         ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `crate::zobrist::*`
  --> lib/engine/src/zobrist.rs:98:9
   |
98 |     use crate::zobrist::*;
   |         ^^^^^^^^^^^^^^^^^

   Compiling tracing-subscriber v0.3.17
warning: variable `bm` is assigned to, but never used
    --> lib/engine/src/board.rs:1209:21
     |
1209 |             let mut bm = bmt;
     |                     ^^
     |
     = note: consider using `_bm` instead
     = note: `#[warn(unused_variables)]` on by default

warning: value assigned to `bm` is never read
    --> lib/engine/src/board.rs:1220:17
     |
1220 |                 bm = bmt;
     |                 ^^
     |
     = help: maybe it is overwritten before being read?
     = note: `#[warn(unused_assignments)]` on by default

warning: constant `RECORD_NONE` is never used
   --> lib/engine/src/board.rs:338:7
    |
338 | const RECORD_NONE: Option<Record> = None;
    |       ^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: field `weight` is never read
  --> lib/engine/src/engine.rs:11:5
   |
7  | pub struct PreLoad {
   |            ------- field in this struct
...
11 |     weight: i32,
   |     ^^^^^^
   |
   = note: `PreLoad` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis

warning: `engine` (lib) generated 6 warnings (run `cargo fix --lib -p engine` to apply 2 suggestions)
   Compiling bytes v1.5.0
^[[Berror: failed to run custom build command for `fltk-sys v1.4.15`

Caused by:
  process didn't exit successfully: `/data/rust_pro/rs-cchess/target/debug/build/fltk-sys-6d6ea200ccee0f5a/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build/android.rs
  cargo:rerun-if-changed=build/bundled.rs
  cargo:rerun-if-changed=build/link.rs
  cargo:rerun-if-changed=build/main.rs
  cargo:rerun-if-changed=build/source.rs
  cargo:rerun-if-changed=build/utils.rs
  cargo:rerun-if-changed=build/fltk_config.rs
  cargo:rerun-if-changed=build/pkg_config.rs

  --- stderr
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
  curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-sys-1.4.15/build/bundled.rs:30:13:
  Download bundled libraries from "https://github.com/MoAlyousef/cfltk/releases/latest/download/lib_x86_64-unknown-linux-gnu.tar.gz" failed
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(base) root@local-xtc:/data/rust_pro/rs-cchess# rustc -V
rustc 1.75.0-nightly (df871fbf0 2023-10-24)

**Comment by lbyczzz** [comment]
1.4.13是一样的，我把lock的这项删了它自动下最新的1.4.15

**Comment by zuisong** [comment]
[MoAlyousef/cfltk/releases/latest/download/lib_x86_64-unknown-linux-gnu.tar.gz](https://github.com/MoAlyousef/cfltk/releases/latest/download/lib_x86_64-unknown-linux-gnu.tar.gz)

你能通过浏览器下载这个文件吗？ 可能需要科学上网环境

**Comment by lbyczzz** [comment]
可以的，下载了安装这个编译器吗

**Comment by zuisong** [comment]
我看日志像是下载这个库超时， 你能下载应该就能正常编译的。 可以再试一次

不行可以可以这样改一下再试一次




```diff
diff --git forkSrcPrefix/lib/ui/Cargo.toml forkDstPrefix/lib/ui/Cargo.toml
index bb7fcfffe5c20296a9057bec87123c9eecc8c73d..84dd4d9fd07dc1b097c94b366003e7b38145688c 100644
--- lib/ui/Cargo.toml
+++ lib/ui/Cargo.toml
@@ -6,7 +6,7 @@ version = "0.1.0"
 [dependencies]
 anyhow = "1.0.75"
 bytes = "1.5.0"
-fltk = {version = "1.4.12", features = ["fltk-bundled"]}
+fltk = {version = "1.4.12"}
 tracing = {version = "0.1.37", features = ["log"]}
 tracing-subscriber = {version = "0.3.17", features = ["env-filter"]}
 engine = { path = "../engine" }
```

**Comment by lbyczzz** [comment]
还是不行，咱这项目支持在win下跑吗

**Comment by zuisong** [comment]
我在mac上运行的  我加一个github action 在多平台上运行测试一下呢

**Comment by lbyczzz** [comment]
我在win下也是报同样的错，然后我才用虚拟机跑，结果还是一样。害

**Comment by zuisong** [comment]
https://github.com/zuisong/rs-chinese-chess/actions/runs/6635462365/

测试了一下  windows 可以正常编译的。ubuntu 缺少什么环境， 编译报错了  报错日志也和你贴出来的不一样

从你贴出的日志信息来看， 报错信息指向 下载文件超时

**Comment by lbyczzz** [comment]
诶，我又在win下跑了下又成功了。。
![image](https://github.com/zuisong/rs-chinese-chess/assets/50623847/e83385c1-98e3-481b-9f50-a1058a38daa7)

**Comment by zuisong** [comment]
跑起来就行   之前写到一半的机器人你可以试着续写一下， 也可以尝试加上网络联机对战， 后面这个比较适合新手区练习rust网络编程

这个问题我就关掉了， 加油！😃

**Comment by lbyczzz** [comment]
好滴，感谢您。我就是想用rust写下AI。
